### ISSUE TITLE
When receiving a list from a for loop it displays wrongly

### ISSUE THREAD

**Issue by gudeliauskaspam** [IngoMeyer441/simple-term-menu#10]
I'm passing a list coming from a for loop as a parameter to form the menu, however, when I choose the options, they start to multiply each time I go down the list and I can't select the one I want.
[Edit: adding example]

The list that I receive from loop
['Tailor ASMR / Beads / Fabrics / Measure / Crinkly Paper / Cutting / Soft Spoken', 'Soft Whispers 💜 Slow Hair Brushing 💜 ASMR 💜 Pleasant White Noise', '✂️ Sleep-inducing Haircut 💇 ASMR | Shampoo | Page Flipping | Scissors ']

Result of when I try to navigate in options (one line from every time I try to choose something, If you keep pressing it will stay that way forever):
Tailor ASMR / Beads / Fabrics / Measure / Crinkly Paper / Cutting / Soft Spoken (StT4wUfcGj4)             
Tailor ASMR / Beads / Fabrics / Measure / Crinkly Paper / Cutting / Soft Spoken (StT4wUfcGj4)
Tailor ASMR / Beads / Fabrics / Measure / Crinkly Paper / Cutting / Soft Spoken (StT4wUfcGj4)
Tailor ASMR / Beads / Fabrics / Measure / Crinkly Paper / Cutting / Soft Spoken (StT4wUfcGj4)
Tailor ASMR / Beads / Fabrics / Measure / Crinkly Paper / Cutting / Soft Spoken (StT4wUfcGj4)

**Comment by IngoMeyer441** [comment]
I can confirm the bug with this minimal example:
```python
#!/usr/bin/env python3

from simple_term_menu import TerminalMenu


menu_entries = [
    "Heart 💜",
    "Scissors ✂️",
]


def main():
    terminal_menu = TerminalMenu(menu_entries)
    terminal_menu.show()


if __name__ == "__main__":
    main()
```
simple-term-menu has problems with unicode emojis, but currently I have no idea why. Internally, it uses Unicode objects, so emojis shouldn't be a problem, actually.

**Comment by IngoMeyer441** [comment]
Ok, it is a problem with wrong handling of double width characters...

**Comment by IngoMeyer441** [comment]
I have added a fix on the current develop branch, but I have to do more tests (on macOS). Do you use a Linux system? In that case, you can try the latest development version of `simple-term-menu` with
```bash
python3 -m pip install git+https://github.com/IngoMeyer441/simple-term-menu.git#develop
```

**Comment by Seluj78** [comment]
Hey @IngoMeyer441 ! Here's a recording of me trying your fix on MacOS 10.14.6. Sadly it didn't work

https://asciinema.org/a/YrApZS4UbZ7fA9pzaRiQQy1Fd

**Comment by IngoMeyer441** [comment]
@Seluj78 Thanks for testing! You installed the stable version from PyPI. The development version can only be installed from this GitHub respository directly.

**Comment by Seluj78** [comment]
@IngoMeyer441 I did use your command further down the recording, did you watch it entirely ?

**Comment by Seluj78** [comment]
<img width="1680" alt="Screenshot 2020-10-20 at 10 14 08" src="https://user-images.githubusercontent.com/4641317/96559203-006a0880-12bd-11eb-8969-291b90c33721.png">

**Comment by IngoMeyer441** [comment]
Sorry, my fault :sweat_smile: 
Ok, I think another library has to be opened on macOS.

**Comment by IngoMeyer441** [comment]
A fix for macOS is added to develop. Could you test again?

**Comment by Seluj78** [comment]
@IngoMeyer441 on it now

**Comment by Seluj78** [comment]
It's working fine on MacOs 🚀

**Comment by IngoMeyer441** [comment]
:+1: The new version is also published. Thanks for the help! :smile:

**Comment by gudeliauskaspam** [comment]
@IngoMeyer441  thanks for the fast response, and yes, I'm using linux system.

**Comment by gudeliauskaspam** [comment]
I fixed the problem in my application by removing the emojis before going to the TerminalMenu input list.

**Comment by IngoMeyer441** [comment]
Ok, I think this issue can now be closed. If you encounter any further problems with emojis or other double width characters please feel free to reopen.
