### ISSUE TITLE
termios.error: (25, 'Inappropriate ioctl for device')

### ISSUE THREAD

**Issue by mperezi** [IngoMeyer441/simple-term-menu#11]
I was using simple-term-menu for writing a git hook when I ran into the following problem:

```
stty: stdin isn't a terminal
Traceback (most recent call last):
  File ".git/hooks/pre-push", line 52, in <module>
    check_versions(local_sha)
  File ".git/hooks/pre-push", line 46, in check_versions
    ask_confirmation(metadata['api']['version'], openapi_rest['info']['version'])
  File ".git/hooks/pre-push", line 33, in ask_confirmation
    if TerminalMenu(["[y] Yes", "[n] No"]).show() == 1:
  File "/Users/miguel.perez/.local/share/virtualenvs/mecrtrrfco-api-ebjNHAQ0/lib/python3.7/site-packages/simple_term_menu.py", line 1002, in show
    self._init_term()
  File "/Users/miguel.perez/.local/share/virtualenvs/mecrtrrfco-api-ebjNHAQ0/lib/python3.7/site-packages/simple_term_menu.py", line 619, in _init_term
    self._old_term = termios.tcgetattr(self._fd)
termios.error: (25, 'Inappropriate ioctl for device')
```

Any ideas? 🤷‍♂️

**Comment by IngoMeyer441** [comment]
The problem in this case is, that Git runs hooks in an non-interactive environment. Therefore, stdout is not directly connected to the terminal which is required by simple-term-menu to work correctly. As a workaround you could try to redirect stdout of the simple-term-menu call to the current tty again, like this:
```bash
simple-term-menu entry1 entry2 entry3 >/dev/tty
```

**Comment by IngoMeyer441** [comment]
Perhaps, I should throw a better error message if simple-term-menu is not connected to a terminal.

**Comment by mperezi** [comment]
My bad. I should've told you that my problem was not about the _why_ but the _how_ (the workaround). I think the message

```
stty: stdin isn't a terminal
```

is pretty self-explanatory. 

That being said, my git hook is written in Python so no chance I can use your proposed solution.

**Comment by IngoMeyer441** [comment]
Could you please try the latest development version? You can install it with
```bash
python3 -m pip install git+https://github.com/IngoMeyer441/simple-term-menu@develop
```
The develop branch contains a commit which reads from and write to the tty directly. This should make simple-term-menu immune against redirects of stdin and stdout.

**Comment by mperezi** [comment]
```
Traceback (most recent call last):
  File ".git/hooks/pre-push", line 52, in <module>
    check_versions(local_sha)
  File ".git/hooks/pre-push", line 46, in check_versions
    ask_confirmation(metadata['api']['version'], openapi_rest['info']['version'])
  File ".git/hooks/pre-push", line 33, in ask_confirmation
    if TerminalMenu(["[y] Yes", "[n] No"]).show() == 1:
  File "/usr/local/lib/python3.8/site-packages/simple_term_menu.py", line 1020, in show
    assert self._tty_out is not None
AssertionError
```
Btw, Python version is 3.8.5

**Comment by IngoMeyer441** [comment]
I'm sorry. I have added this assertion without testing. :sweat_smile: It was one line to early. Could you please test again? Now it should really work.

**Comment by mperezi** [comment]
It works like a charm now. Thank you! 🤗

**Comment by IngoMeyer441** [comment]
Great, thanks for testing! Release [v0.10.4](https://github.com/IngoMeyer441/simple-term-menu/releases/tag/v0.10.4) is out which contains the changes. Have fun! :smile:
