### ISSUE TITLE
cursor_index doesn't exist

### ISSUE THREAD

**Issue by gustavwilliam** [IngoMeyer441/simple-term-menu#15]
Thanks for creating this library — it's pretty nice. However, I need to set an initial menu item, but can't manage to do it. Following your README.md, it seems like the following would be possible:
```py
terminal_menu = TerminalMenu(
    [
        "Item 0",
        "Item 1",
        "Item 2",
    ],
    cursor_index=1,
)
```

However, when I try this, I get the following exception:
```py
Traceback (most recent call last):
  File "user_interface.py", line 15, in <module>
    cursor_index=2,
TypeError: __init__() got an unexpected keyword argument 'cursor_index'
```

Passing it as `terminal_menu.cursor_index = 2` doesn't give me an error, but it also doesn't change the initial index. Is there something that I have missed, or is there a bug at play?

**Comment by IngoMeyer441** [comment]
Thanks for trying simple-term-menu. The `cursor_index` argument is quite new and not part of any release yet. So if you installed this package with pip, it came without `cursor_index`. I can make a new release tomorrow morning, then you can install an update and the example from the readme should work.

**Comment by gustavwilliam** [comment]
Ah, I see. Thanks; that would be excellent. I'm really liking this library so far 😄

**Comment by IngoMeyer441** [comment]
v0.10.5 is released on PyPI and includes all recent changes of the `develop` branch. :tada:

**Comment by gustavwilliam** [comment]
Fantastic; thanks!

**Comment by IngoMeyer441** [comment]
I think this issue is solved so I close it. Please feel free to reopen if you encounter any further problems.
