### ISSUE TITLE
Render UTF-8 characters in preview panel

### ISSUE THREAD

**Issue by NamamiShanker** [IngoMeyer441/simple-term-menu#23]
Hey @IngoMeyer44,1 thanks for making this amazing library!

I was trying to render some characters in the preview panel and I ran into a bit of a problem. Some characters are not printed correctly in the preview panel. Please see the image below -

![screenshot](https://user-images.githubusercontent.com/26577306/115962581-c1ea2a80-a539-11eb-9486-b96ed1a5ab34.png)

The boxes around the headings and code blocks in the above picture are made of `?`, which instead should look like that in the image below - 
![](https://user-images.githubusercontent.com/26577306/115892440-c4cf1780-a474-11eb-9143-0ef981a68f4c.png)

This is probably happening because the preview panel is using `ASCII` encoding instead of `UTF-8`. Can you please add a support for `UTF-8` characters? Or maybe guide me so that I myself can fix it and make a PR?

**Comment by IngoMeyer441** [comment]
Hey @NamamiShanker,
thanks for using my library. :+1: `simple-term-menu` has built-in UTF-8 support but falls back to ASCII if it detects that the system is not configured for UTF-8. The code uses the result of `locale.getlocale()[1]` for the detection part. Could you check what this code snippet returns for you?

This code example:
```python
#!/usr/bin/env python3

import os
import subprocess

from rich.console import Console
from rich.markdown import Markdown

from simple_term_menu import TerminalMenu

columns = int(subprocess.check_output(["tput", "cols"], universal_newlines=True))


def print_box(filepath):
    console = Console(width=columns - 4)
    with console.capture() as capture:
        console.print(Markdown("# File {}".format(filepath)))

    return capture.get()


def list_files(directory="."):
    return (file for file in os.listdir(directory) if os.path.isfile(os.path.join(directory, file)))


def main():
    terminal_menu = TerminalMenu(list_files(), preview_command=print_box, preview_size=0.75)
    terminal_menu.show()


if __name__ == "__main__":
    main()
```
draw boxes with Unicode characters for me:
![image](https://user-images.githubusercontent.com/1449087/116049512-a6d10500-a676-11eb-8893-14f0e327e186.png)

**Comment by NamamiShanker** [comment]
Thank you so much! My terminal was not configured for UTF-8 characters. I changed my terminal's locale and now it works like a charm.

**Comment by IngoMeyer441** [comment]
Great!
