### ISSUE TITLE
Options to preview without the preview box

### ISSUE THREAD

**Issue by dinghino** [IngoMeyer441/simple-term-menu#24]
Since the preview command can take a function to actually do whatever you want with the currently selected field, that's pretty powerful.

Currently I was thinking to use it to output a text to explain what the select option actually does, and both the frame and especially the _preview_ (the word) are actually misleading.

This I think could be done with some new optional arguments to pass when creating the menu object, like `create_preview_border=True` and `preview_header="preview"` or something like that.

**Comment by IngoMeyer441** [comment]
Hey and thanks for using my library! :blush: 
You are right, the preview window could be more abstract or universal. If the border is hidden, I think we need some kind of other separator to make clear the "preview" text is not part of the menu itself. Or do you think users should care themselves to insert some kind of space or separator in this case?

**Comment by dinghino** [comment]
maybe even just a couple of blank lines to separate the preview output from the menu, or an optional single line could do.

For my use case it's pretty obvious that it's not part of the menu, for example, and when you want to use it as an actual preview it is actually nice to have the _container_ to separate it explicitly

I tried mingling around with the source and managed to remove the border but then i had issues with the lines staying where they are suppose to, probably due to some missing or extra `\r` characters

**Comment by IngoMeyer441** [comment]
The latest `develop` branch add two new parameters to the `TerminalMenu` constructor:

- `preview_border`: Bool which defaults to `True` and can be used to deactivate the preview border completely.
- `preview_title`: Sets the preview title. Disappears if `preview_border` is set to `False`.

You can try the latest development version by installing it directly from GitHub instead of PyPI:
```bash
python3 -m pip install git+https://github.com/IngoMeyer441/simple-term-menu@develop
```
Is this already what you need?

**Comment by IngoMeyer441** [comment]
Currently, no blank lines are inserted if `preview_border` is `False`.

**Comment by IngoMeyer441** [comment]
The changes are now in the latest [v1.2.0](https://github.com/IngoMeyer441/simple-term-menu/releases/tag/v1.2.0) release. Feel free to reopen if you still miss anything or find any bugs.
