### ISSUE TITLE
Localization option for hints

### ISSUE THREAD

**Issue by muellma-items** [IngoMeyer441/simple-term-menu#26]
Hi there,

first of all thanks for this great module!
Have you thought about adding localization options for the hints? Currently we can enable the hints with the parameters 
`show_search_hint`, `show_shortcut_hints `and `show_multi_select_hint`. What about additional properties like
`show_search_hint_text`, `show_shortcut_hints_text `and `show_multi_select_hint_text `where the user can set the text to be displayed as a hint?
So for example it would be 
`show_multi_select_hint=True, show_multi_select_hint_text="Press <space> for multi-selection and <enter> to accept"`

In my opinion it would not be necessary for the localized text to support dynamic key names.

**Comment by IngoMeyer441** [comment]
The latest `develop` adds `show_multi_select_hint_text` and `show_search_hint_text`. I skipped `show_shortcut_hints_text` since it only repeats the shortcuts with menu entries in the title or status bar. You can try the latest version with
```bash
python3 -m pip install git+https://github.com/IngoMeyer441/simple-term-menu
```
What do you think about this?

**Comment by IngoMeyer441** [comment]
Simple example for testing:
```python
#!/usr/bin/env python3

from simple_term_menu import TerminalMenu


def main():
    fruits = ["[a] apple", "[b] banana", "[o] orange"]
    terminal_menu = TerminalMenu(
        fruits,
        title="Fruits",
        show_search_hint=True,
        show_search_hint_text="Press {key} for searching!!!",
        multi_select=True,
        show_multi_select_hint=True,
        show_multi_select_hint_text="Press {accept_keys} for accepting and {multi_select_keys} for selecting!",
    )
    terminal_menu.show()


if __name__ == "__main__":
    main()
```

**Comment by IngoMeyer441** [comment]
![image](https://user-images.githubusercontent.com/1449087/119156486-908b4e80-ba54-11eb-94d9-7a6572e8229c.png)

**Comment by IngoMeyer441** [comment]
The changes are now in the latest [v1.2.0](https://github.com/IngoMeyer441/simple-term-menu/releases/tag/v1.2.0) release. Feel free to reopen if you still miss anything or find any bugs.
