### ISSUE TITLE
Search breaks multiselect

### ISSUE THREAD

**Issue by svartkanin** [IngoMeyer441/simple-term-menu#39]
Search in multi-select doesn't work as expected. The search itself will display only the matching entries but will keep all rows (with blank for non-matching). When then pressing SPACE on a selection everything vanishes and nothing gets selected. 

![first](https://user-images.githubusercontent.com/19396770/136549005-b0fb5488-4f46-415a-841e-bc9e89ddbd32.png)

Now searching somethign

![second](https://user-images.githubusercontent.com/19396770/136549093-dcc2a641-80d2-4ceb-ba9e-248e01dafff8.png)

And now pressing SPACE

![third](https://user-images.githubusercontent.com/19396770/136549179-f492c16e-05a1-4936-b025-d09a6c16bbb4.png)

**Comment by svartkanin** [comment]
Are there any updates on this bug fix?

**Comment by IngoMeyer441** [comment]
Sorry, I didn't have time yet to look into this. I try to fix it in the next days.

**Comment by IngoMeyer441** [comment]
Should be fixed in the latest `develop`. Could you please test this by installing from GitHub directly?
```bash
python3 -m pip install git+https://github.com/IngoMeyer441/simple-term-menu@develop
```
Since `space` is used as input in search mode, you can use `tab` to add or remove selections.

**Comment by svartkanin** [comment]
@IngoMeyer441 I tested it and it seems to work fine, thanks!
