### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by Torxed** [IngoMeyer441/simple-term-menu#42]
Hi.

Since discussions is not unlocked on this project here at GitHub, I'll create an issue and I hope that's okay. Apologies if it's not!

We *(the archinstall project)* would like to include this project in our source code when we ship [archinstall](https://github.com/archlinux/archinstall).
The reason being that this project is not in the official Arch Linux repository for reasons we can discuss at some point. But this means we cannot specify this project as a dependency and get it shipped automatically together with our project *(as a Arch Linux dependency, pip works but not the distro shipping)*.

According to the MIT guidelines, and I'm not a legal ninja, this should be fine as long as we contribute the work to you the creator or rights holder. And that we include the *(MIT)* license in the [header of the source file](https://github.com/archlinux/archinstall/blob/638f970e9b8fdaa147bc169de25ddf60bfa6a23a/archinstall/lib/simple_menu.py#L7-L70) that we copy over. Never the less, I would just like to double check with this project that it would be okay to do so. I don't want to stir up any trouble or hard feelings anywhere for doing so, and I hope that my explanation shows why we have to do this.

We're fully aware that we won't get updates automatically, but we're fine with that for now.
Any comments, thoughts or objections are welcome and feel free to close this if it's a non-issue : )

Thank you in advance, and here is the PR that would introduce it *(WIP)*: https://github.com/archlinux/archinstall/pull/660
//The creator of the archinstall project

**Comment by IngoMeyer441** [comment]
Hi @Torxed,
I would be very pleased if I can help to make other projects better. I am not the copyright holder (since I initially wrote it at work for another internal project) but my employer is willing to support open-source software. So your suggestion to adopt the source code and keep the copyright notice is totally fine. :+1:

**Comment by Torxed** [comment]
> Hi @Torxed, I would be very pleased if I can help to make other projects better. I am not the copyright holder (since I initially wrote it at work for another internal project) but my employer is willing to support open-source software. So your suggestion to adopt the source code and keep the copyright notice is totally fine. +1

Awesome, thank you @IngoMeyer441 for the swift response!
We'll go ahead and merge our PR later this month.

Thanks go out to you and your employer!
