### ISSUE TITLE
Scrolling through long Menu is extremly slow or crashes

### ISSUE THREAD

**Issue by MangoSven** [IngoMeyer441/simple-term-menu#49]
When i got a long list of items in my Menu and i hold the down key the scrolling is extremly slow.
If i activate `search_key=None` and hold the down key, the menu crashes after the third entry.

The Menu:

![simple-term-menu_menu](https://user-images.githubusercontent.com/7713227/166878612-8c07ee86-7e11-4cae-bdd2-c67d724cf9a9.PNG)

Crashlog with `search_key=None`

![simple-term_menu_log](https://user-images.githubusercontent.com/7713227/166879293-5aea4b84-25b1-4bdb-a250-41163a941129.PNG)

**Comment by IngoMeyer441** [comment]
Thanks for your bug report. I tried to reproduce this behavior with
```python
#!/usr/bin/env python3

from simple_term_menu import TerminalMenu


def main():
    terminal_menu = TerminalMenu(
        [f"veeeeeeeeeeeeeeeeeeerrrrrrrrrrrrrrrrrrrry long item {i}" for i in range(1000)],
        search_key=None,
    )
    menu_entry_indices = terminal_menu.show()
    print(menu_entry_indices)
    print(terminal_menu.chosen_menu_entries)


if __name__ == "__main__":
    main()
```
but could neither produce the crash nor get a slowdown. Could you please send an example code? Which version of simple-term-menu do you use?

**Comment by MangoSven** [comment]
Very Strange. On my pc  at Home i dont get it either. I will look onto it at my work computer in a few days and give you a little exmaple code, if i can extract it

**Comment by MangoSven** [comment]
The Bug is gone. I tested the script under WSL1 and after upgrading to WSL2 this behaveor is gone.

**Comment by IngoMeyer441** [comment]
Thanks for the feedback! I think WSL 1 can be considered obsolete, so we don't need to look into this further...
