### ISSUE TITLE
Control menu-cancel character

### ISSUE THREAD

**Issue by bhakta0007** [IngoMeyer441/simple-term-menu#54]
How can I prevent Escape key from canceling the menu.

Can this be controlled?

I use in GNU screen environment, and I use screen scroll / search up and down. Escape is what I use to come back to normal mode from selection mode. 

I would like to restrict the menu cancel to "q" and "ctrl-c"

**Comment by IngoMeyer441** [comment]
This is now implemented in the [latest `develop` version](https://github.com/IngoMeyer441/simple-term-menu/commit/9def4f8d4d33a85ff23f70a25f96f6a12de48f01). You can install it with

```bash
python3 -m pip install https://github.com/IngoMeyer441/simple-term-menu@develop
```

Pass `quit_keys=("q", )` to the `TerminalMenu` constructor to only allow `q` and `<Ctrl-c> to exit the menu.

**Comment by IngoMeyer441** [comment]
The new feature is also part of the latest release `v1.5.0`. Feel free to reopen if the new feature does not correctly work for you.

**Comment by bhakta0007** [comment]
@IngoMeyer441 thank for getting this done, I will give it a shot
