### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by TechWiz-3** [IngoMeyer441/simple-term-menu#67]
First of all, thank you so much for your work on this project.

I'm receiving this error on `Ubuntu 22.04`. I download and extract a binary build of [my script](https://github.com/TechWiz-3/git-cheatsheet/blob/binaries/gcheat.py) (which uses simple-term-menu) from [here](https://github.com/TechWiz-3/git-cheatsheet/actions/runs/3112920813). When I run it though, I get the follow error:
```py
tput: /tmp/_MEIRdZD9q/libtinfo.so.6: version `NCURSES6_TINFO_6.2.current' not found (required by tput)
Traceback (most recent call last):
  File "gcheat.py", line 107, in <module>
    render_main_menu()
  File "gcheat.py", line 51, in render_main_menu
    main_menu = TerminalMenu(choices, title="Git topics:")
  File "simple_term_menu.py", line 764, in __init__
  File "simple_term_menu.py", line 403, in __init__
  File "simple_term_menu.py", line 483, in preview_lines_count
  File "simple_term_menu.py", line 885, in _num_lines
ValueError: invalid literal for int() with base 10: ''
```

The weird thing is, if I run the same binary-building commands locally on my Ubuntu VM, the binary works perfectly fine.
Any ideas what the error could be?

**Comment by IngoMeyer441** [comment]
Hey and thanks for using simple-term-menu :smile:.
[Line 885](https://github.com/IngoMeyer441/simple-term-menu/blob/develop/simple_term_menu.py#L885) uses the `tput` command to get the height of the terminal, but `tput` in your build does not match the installed ncurses version (`NCURSES6_TINFO_6.2.current' not found`). I would guess that ncurses is missing on the test system.

**Comment by TechWiz-3** [comment]
Yup thank you, that's what it turned out to be. I've got some weird things going on with that ubuntu instance 😅 
I tried it on another instance and it worked.
