### ISSUE TITLE
Error with multi_select

### ISSUE THREAD

**Issue by allenweiss** [IngoMeyer441/simple-term-menu#70]
When I use this code that was posted as an example of multi-select. I get an error. Note, I used this simple-term-menu with no problems as long as I don't do a multi-select.

TypeError: __init__() got an unexpected keyword argument 'multi_select'

from simple_term_menu import TerminalMenu

def main():
    terminal_menu = TerminalMenu(
        ["dog", "cat", "mouse", "squirrel"],
        multi_select=True,
        show_multi_select_hint=True,
    )
    menu_entry_indices = terminal_menu.show()
    print(menu_entry_indices)
    print(terminal_menu.chosen_menu_entries)

if __name__ == "__main__":
    main()

**Comment by IngoMeyer441** [comment]
Thanks for your report. I tried the example and it works for me. Do you perhaps use a quite old version of simple_term_menu? Multi-select was added in version `0.11.0` and the latest version is `1.5.2`. You can check the installed version with:

```bash
python -c 'from simple_term_menu import __version__; print(__version__)'
```

**Comment by allenweiss** [comment]
Thanks..I guess I'm running 0.10.4...so how do I update to the latest version?

**Comment by IngoMeyer441** [comment]
Did you install with pip? In this case 

```bash
python3 -m pip install -U simple_term_menu
```

should do the trick.

**Comment by allenweiss** [comment]
Thanks so much...that worked....really like the plugin.
