### ISSUE TITLE
tput: No value for $TERM and no -T specified 

### ISSUE THREAD

**Issue by error13** [IngoMeyer441/simple-term-menu#76]
on Linux Mint 19 Cinnamon

to reproduce:
     from simple_term_menu import TerminalMenu

     terminal_menu = TerminalMenu(["entry 1", "entry 2", "entry 3"])
     terminal_menu.show()

tput: No value for $TERM and no -T specified
line 3, in <module>
    terminal_menu = TerminalMenu(["entry 1", "entry 2", "entry 3"])

very new to python and programing so forgive me if this is easily fixed

**Comment by IngoMeyer441** [comment]
Hey @error13 and welcome to Python programming!
The `TERM` variable is usually set by your terminal emulator and is used by `tput` to generate the correct control codes for things like cursor movement, text formatting and others. Which terminal emulator do you use?

**Comment by error13** [comment]
Terminator

**Comment by IngoMeyer441** [comment]
As a first workaround you could call Python like this:

```bash
TERM=xterm-256color python
```

But I don't know why this is necessary for your setup. I will fetch Linux Mint 19 and try to run simple-term-menu with Terminator.

**Comment by IngoMeyer441** [comment]
I cannot reproduce your problem on a fresh Linux Mint 19 Cinnamon in Terminator :disappointed:.

**Comment by error13** [comment]
interesting... i did manage to get the code to run correctly  with the work around.  TERM=xterm-256color python. i will have to try it in a virtualBox  running a different version of mint. and see what happens. its not a bug on your part. so  thank you for your help!  its a very nice program
