### ISSUE TITLE
Quick shortcuts assignment

### ISSUE THREAD

**Issue by Seluj78** [IngoMeyer441/simple-term-menu#8]
It would be awesome to be able to define one or two quick options like `exit` or `go back` (customisable) and mappable to different keys !

For example:

```
> aaa
bbb
ccc
ddd
(q) Exit
(;) Go Back
```

**Comment by IngoMeyer441** [comment]
Adding shortcuts is a good idea :+1:.

**Comment by buanzo** [comment]
Hi! I would like to execute different things depending on which hotkey I press when highlighting an item (alt+D = delete item, etc), so I guess its an extension of this idea...

**Comment by buanzo** [comment]
OK, so the main issue with my requirement is that the return value is the index. Maybe that could be a tuple (index, key_pressed) if the TerminalMenu instance is configured accordingly?

**Comment by IngoMeyer441** [comment]
> OK, so the main issue with my requirement is that the return value is the index. Maybe that could be a tuple (index, key_pressed) if the TerminalMenu instance is configured accordingly?

That would be possible for the Python api but not for the command line version. Hmm, maybe the command line version could print the result to stdout if a tuple is required?

**Comment by IngoMeyer441** [comment]
Ah no, forget the last comment, simple-term-menu cannot be used in Bash process substitutions...

**Comment by Seluj78** [comment]
Is anyone working on this ? :grin: I don't know for sure if I will have the time to try and cook a PR for it

**Comment by IngoMeyer441** [comment]
Currently not. Maybe, I can find some time.

**Comment by IngoMeyer441** [comment]
Version [v0.8.0](https://github.com/IngoMeyer441/simple-term-menu/releases/tag/v0.8.0) includes support for shortcuts by prepending single keys in square brackets before every menu entry. Have a look at the [README](https://github.com/IngoMeyer441/simple-term-menu#shortcuts) for more info.
@buanzo That is still not what you need. Maybe, we could add support for multple shortcut keys and set the pressed key in a property of the `TermMenu` instance? Or do you simply want to press modifier keys when selecting a shortcut?

**Comment by buanzo** [comment]
Hi! Modifier keys were just an example. The alternative you suggest sounds useful.

My use case involves dynamically generated menu items that are in fact elements (for example, members of a mailing list) upon which I would like different actions to be applicable.

I am attempting to avoid convoluted workflows in multi level menues.

**Comment by IngoMeyer441** [comment]
Ah I see. So actually, you don't need a shortcut key to jump to a specific entry. You need different keys to accept a selected menu entry. I think, now I got it right.

**Comment by IngoMeyer441** [comment]
@buanzo: v0.9.0 is released and adds configurable accept keys. You can now do something like:
```python
#!/usr/bin/env python3

import os
from simple_term_menu import TerminalMenu


def main():
    terminal_menu = TerminalMenu(["entry 1", "entry 2", "entry 3"], accept_keys=("enter", "alt-d", "ctrl-i"))
    terminal_menu.show()
    print(terminal_menu.chosen_accept_key)


if __name__ == "__main__":
    main()
```
to distinguish different accept keys and or modifiers.

**Comment by buanzo** [comment]
That's wonderful! Thank you. I will rewrite parts of mailman 3 commander to take advantage of this asap.

**Comment by Seluj78** [comment]
It's working like a charm ! Another request that goes with it is to be able to add it on the top row or sticky bottom so we can see it at all times even with long lists

Example:
```
My title ([q] to Exit [;] Go Back)
> aaa
bbb
ccc
ddd
```

Sorry for being kinda picky ;) But it's already freaking amazing ! 🙌

**Comment by IngoMeyer441** [comment]
Starting with v0.10.0 you can pass `show_shortcut_hints=True` to the `TerminalMenu` constructor to display a title line with shortcut hints.

**Comment by Seluj78** [comment]
It's perfect ! Thanks !

I'm closing the issue, feel free to reopen it if you want to add more to this feature request !

Thanks for all the hard and quick work !
