### ISSUE TITLE
Cannot import library without TERM env variable

### ISSUE THREAD

**Issue by redtomato74** [IngoMeyer441/simple-term-menu#83]
Hi,

We cannot import simple-term-menu package anymore since it checks for TERM environment variable.
I understand, that TERM might be required for this package to work, but the missing variable shouldn't block import right away, right?

For example, some script can accept parameters both as options and in interactive mode, we use the first way in CI and the second way while running locally. Checking for TERM breaks all CI builds, just because code checks for TERM variable on import. Plus that change was introduced in a patch version update.

Can you please fix this (for example by moving that check deeper, to some function/method, which actually relies on real terminal)?

Thanks

**Comment by IngoMeyer441** [comment]
Thanks for the issue. This is fixed in release [v1.6.3](https://github.com/IngoMeyer441/simple-term-menu/releases/tag/v1.6.3). Please reopen, if you still have any problems left.
