### ISSUE TITLE
Can't search for accented options

### ISSUE THREAD

**Issue by f3rn4nd0-c354r** [IngoMeyer441/simple-term-menu#85]
Hello, 

When using search (`/`) I see cases are ignored, but accents are not. However I'm not able to use accents in search (both the accent and other character are not displayed)  making it impossible to find some items.

Example:

```
from simple_term_menu import TerminalMenu

def main():
    options = ["Abóbora", "Maçã", "Ananás/"]
    terminal_menu = TerminalMenu(options)
    menu_entry_index = terminal_menu.show()
    print(f"You have selected {options[menu_entry_index]}!")

if __name__ == "__main__":
    main()
```

**Comment by IngoMeyer441** [comment]
Thanks for the bug report. This is fixed in version `v1.6.4`, German umlauts and accented letters can now be typed into the search line. Feel free to reopen if any issues are left.
