### ISSUE TITLE
simple_term_menu not found

### ISSUE THREAD

**Issue by lazlow3** [IngoMeyer441/simple-term-menu#9]
I wrote a simple script in Python 3.7 with simple-term-menu which runs fine from the command line. I added the .py to run from rc.local so it runs at boot but I keep getting an error that simple_term_menu can't be found when it trys to run the program at boot. I've looked at the pathing and everything looks correct. I'm kind of stuck on this. Any ideas?

**Comment by IngoMeyer441** [comment]
`rc.local` is run by the root user. Did you maybe install simple-term-menu only for your current user? You can check the install location with these lines in an interactive Python session:
```python
import simple_term_menu
print(simple_term_menu.__file__)
```
A system wide installation should be located in `/usr/lib` or `/usr/local/lib`.

But even if simple-term-menu starts, you will probably have some issues with an interactive command in `rc.local`. As far as I know, rc.local is not connected to stdin of the Linux terminal, so your script won't receive any input. However, [there is already a similar question on superuser](https://superuser.com/questions/584931/howto-start-an-interactive-script-at-ubuntu-startup) that may help you.

**Comment by lazlow3** [comment]
It looks like it is installing to /home/pi/.local. I'll see if I can install it to the correct location. I used python3 -m pip install simple-term-menu to install it.

**Comment by IngoMeyer441** [comment]
Could you try
```bash
sudo python3 -m pip install simple-term-menu
```
instead? As the root user it should be installed system-wide on a Raspbian.

**Comment by lazlow3** [comment]
I was able to work it out without reinstalling. I was able to trigger the script from /etc/profile from startup/reboot.
