### ISSUE TITLE
type object is not subscriptable

### ISSUE THREAD

**Issue by vissieGP** [IngoMeyer441/simple-term-menu#96]
Hi. I am trying to run your demo code on a new VPS that I have. It runs very well on lots of other VPS'es and PCs of mine. 

    #!/usr/bin/env python3

    from simple_term_menu import TerminalMenu

    def main():
        options = ["entry 1", "entry 2", "entry 3"]
        terminal_menu = TerminalMenu(options)
        menu_entry_index = terminal_menu.show()
        print(f"You have selected {options[menu_entry_index]}!")

    if __name__ == "__main__":
        main()

I get the following error:
    
    Traceback (most recent call last):
      File "./test.py", line 14, in <module>
        main()
      File "./test.py", line 10, in main
        menu_entry_index = vis.show()
      File "/usr/local/lib/python3.7/dist-packages/simple_term_menu.py", line 1515, in show
        self._init_term()
      File "/usr/local/lib/python3.7/dist-packages/simple_term_menu.py", line 975, in _init_term
        cast(list[bytes], self._new_term[6])[termios.VMIN] = b"\x01"
    TypeError: 'type' object is not subscriptable

I have tried lots of iterations, but nothing works to get this fixed. Please can you try and shed some light on this for me? 
I'm running Debian 10 with python 3.7

**Comment by IngoMeyer441** [comment]
Thanks for your report. The last release added the line you are referring to. By accident, I used `list[bytes]` instead of `List[bytes]`. `list[bytes]` is only compatible with Python >= 3.9. I have fixed this in the latest release, that will be published in the next minutes. Could you please try to upgrade to version 1.6.6?

**Comment by vissieGP** [comment]
1.6.6 Worked for me, thank you very much!
